[package]
name = "formula-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
magnus = { version = "0.7", features = ["embed"] }

[build-dependencies]
magnus = { version = "0.7", features = ["embed"] }
